### ISSUE TITLE
Deployment failing on ApiDistribution

### ISSUE THREAD

**Issue by drissamri** [DanteInc/serverless-multi-regional-plugin#3]
Thank you for your great contribution to the Serverless framework. If I get this working it would solve a big need I currently have without having to do manual setup and/or custom scripts.

I'm have tried to get a multi-region simple lambda deployment working with your plugin but I keep running into this exception:
```
Serverless Error ---------------------------------------
 
  An error occurred: ApiDistribution - The parameter originPath contains one or more parameters that are not valid. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: fc9ef0d6-b069-11e9-847d-7d401a444634).
```

Here you can find my example: https://github.com/drissamri/serverless-multi-region-bug/tree/serverless-multi-regional-plugin

I've had some more luck with the forked plugin `serverless-multi-region-plugin` but run into some other annoyances: https://github.com/unbill/serverless-multi-region-plugin/pull/1

**Comment by jgilbert01** [comment]
thx for posting this issue. i just publish 1.0.5 with a fix
